   
-- cleanup existing data 
   
DROP TABLE GRADES CASCADE CONSTRAINTS;
DROP TABLE COURSES CASCADE CONSTRAINTS;
DROP TABLE STUDENTS CASCADE CONSTRAINTS;
DROP TABLE TEACHERS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_TEA;
DROP SEQUENCE SEQ_COU;
DROP SEQUENCE SEQ_STU;
DROP SEQUENCE SEQ_GRA;

   
-- Squence with increment by 1 
   
CREATE SEQUENCE SEQ_TEA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COU START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STU START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GRA START WITH 1 INCREMENT BY 1;

   
-- Create Tabels 
   
CREATE TABLE TEACHERS (
    T_ID NUMBER PRIMARY KEY,
    T_NAME VARCHAR2(30 BYTE),
    T_TITLE VARCHAR2(12 BYTE)
);

CREATE TABLE COURSES (
    C_ID NUMBER PRIMARY KEY,
    C_TITLE VARCHAR2(30 BYTE),
    C_TEACHER NUMBER,
    C_C_POINTS NUMBER,
    CONSTRAINT F_K_C_T FOREIGN KEY (C_TEACHER) REFERENCES TEACHERS(T_ID)
);

CREATE TABLE STUDENTS (
    ST_ID NUMBER PRIMARY KEY,
    ST_NAME VARCHAR2(30),
    ST_SURNAME VARCHAR2(30),
    ST_ID_NUM VARCHAR2(9),
    ST_GROUP NUMBER
);

CREATE TABLE GRADES (
    G_ID NUMBER PRIMARY KEY,
    G_COURSE NUMBER,
    G_STUDENT NUMBER,
    G_GRADE NUMBER,
    G_DATE DATE,
    CONSTRAINT F_K_G_C FOREIGN KEY (G_COURSE) REFERENCES COURSES(C_ID),
    CONSTRAINT F_K_G_S FOREIGN KEY (G_STUDENT) REFERENCES STUDENTS(ST_ID)
);
