-- Q1
SELECT s.ST_ID, s.ST_NAME, s.ST_SURNAME, 
       COUNT(DISTINCT g.G_GRADE) AS DIFFERENT_GRADES_COUNT
FROM STUDENTS s
JOIN GRADES g ON s.ST_ID = g.G_STUDENT
GROUP BY s.ST_ID, s.ST_NAME, s.ST_SURNAME;   

-- Q2
SELECT *
FROM GRADES
WHERE EXTRACT(DAY FROM G_DATE) <= 10;   

-- Q3
SELECT C_ID, C_TITLE, LENGTH(C_TITLE) AS TITLE_LENGTH
FROM COURSES
ORDER BY LENGTH(C_TITLE) ASC;   

-- Q4
SELECT *
FROM COURSES
WHERE C_C_POINTS < 4;   

-- Q5
SELECT c.C_TITLE, t.T_NAME
FROM COURSES c
JOIN TEACHERS t ON c.C_TEACHER = t.T_ID;   

-- Q6
SELECT t.T_NAME AS TEACHER_NAME, 
       c.C_TITLE AS COURSE_TITLE, 
       g.G_GRADE
FROM GRADES g
JOIN COURSES c ON g.G_COURSE = c.C_ID
JOIN TEACHERS t ON c.C_TEACHER = t.T_ID
JOIN STUDENTS s ON g.G_STUDENT = s.ST_ID
WHERE g.G_GRADE >= 4 
  AND s.ST_ID_NUM = '081RDB141';   

-- Q7
DELETE FROM GRADES
WHERE G_STUDENT = 1 AND G_COURSE = 2;   

-- Q8
UPDATE STUDENTS
SET ST_ID_NUM = '101RDB999'
WHERE ST_ID = 1;   

-- Q9
ALTER TABLE STUDENTS ADD ST_EMAIL VARCHAR2(50);   
-- Double check 
SELECT * FROM STUDENTS;

-- Q10
SELECT G_ID, G_COURSE, G_STUDENT, G_GRADE, G_DATE,
       TRUNC(MONTHS_BETWEEN(SYSDATE, G_DATE)) AS FULL_MONTHS_AGO
FROM GRADES;   

-- Q11
SELECT s.ST_ID, s.ST_NAME, s.ST_SURNAME,
       ROUND(AVG(g.G_GRADE), 1) AS AVG_ROUND_TENTH,
       FLOOR(AVG(g.G_GRADE))    AS AVG_SMALLER_INTEGER,
       CEIL(AVG(g.G_GRADE))     AS AVG_GREATER_INTEGER
FROM STUDENTS s
JOIN GRADES g ON s.ST_ID = g.G_STUDENT
GROUP BY s.ST_ID, s.ST_NAME, s.ST_SURNAME;   

-- Q12
SELECT ST_ID, ST_NAME, ST_SURNAME, ST_ID_NUM,
       TO_NUMBER('20' || SUBSTR(ST_ID_NUM, 1, 2)) AS START_YEAR
FROM STUDENTS;   

-- Q13
SELECT s.ST_ID, s.ST_NAME, s.ST_SURNAME, 
       ROUND(AVG(g.G_GRADE), 2) AS AVG_GRADE
FROM STUDENTS s
JOIN GRADES g ON s.ST_ID = g.G_STUDENT
GROUP BY s.ST_ID, s.ST_NAME, s.ST_SURNAME
ORDER BY AVG_GRADE DESC;   

-- Q14
SELECT s.ST_ID, s.ST_NAME, s.ST_SURNAME, 
       COUNT(DISTINCT g.G_COURSE) AS EXAMS_PASSED
FROM STUDENTS s
JOIN GRADES g ON s.ST_ID = g.G_STUDENT
WHERE g.G_GRADE >= 4
GROUP BY s.ST_ID, s.ST_NAME, s.ST_SURNAME
HAVING COUNT(DISTINCT g.G_COURSE) = 6;   

-- Q15
SELECT s.ST_ID, s.ST_NAME, s.ST_SURNAME, 
       ROUND(AVG(g.G_GRADE), 2) AS AVG_GRADE
FROM STUDENTS s
JOIN GRADES g ON s.ST_ID = g.G_STUDENT
GROUP BY s.ST_ID, s.ST_NAME, s.ST_SURNAME
HAVING AVG(g.G_GRADE) > (
    SELECT AVG(g2.G_GRADE)
    FROM GRADES g2
    JOIN STUDENTS s2 ON g2.G_STUDENT = s2.ST_ID
    WHERE s2.ST_ID_NUM = '061RDB121'
);   

-- Q16
SELECT s.ST_ID, s.ST_NAME, s.ST_SURNAME, s.ST_ID_NUM,
       TO_NUMBER('20' || SUBSTR(s.ST_ID_NUM, 1, 2)) AS START_YEAR,
       ROUND(AVG(g.G_GRADE), 2) AS AVG_GRADE
FROM STUDENTS s
JOIN GRADES g ON s.ST_ID = g.G_STUDENT
GROUP BY s.ST_ID, s.ST_NAME, s.ST_SURNAME, s.ST_ID_NUM
HAVING AVG(g.G_GRADE) > (
    SELECT AVG(g2.G_GRADE)
    FROM GRADES g2
    JOIN STUDENTS s2 ON g2.G_STUDENT = s2.ST_ID
    WHERE s2.ST_ID_NUM = '061RDB121'
)
ORDER BY START_YEAR ASC;   

-- Q17
SELECT t.T_NAME AS TEACHER_NAME,
       c.C_TITLE AS COURSE_TITLE,
       ROUND(AVG(g.G_GRADE), 2) AS AVG_GRADE
FROM GRADES g
JOIN COURSES c ON g.G_COURSE = c.C_ID
JOIN TEACHERS t ON c.C_TEACHER = t.T_ID
GROUP BY GROUPING SETS ((t.T_ID, t.T_NAME), (c.C_ID, c.C_TITLE)); --[cite: 1, 2]

-- Q18
SELECT t.T_ID, t.T_NAME,
       ROUND(AVG(g.G_GRADE), 2) AS TEACHER_AVG,
       ROUND((SELECT AVG(G_GRADE) FROM GRADES), 2) AS DB_AVG,
       ROUND(ABS(AVG(g.G_GRADE) - (SELECT AVG(G_GRADE) FROM GRADES)), 2) AS DIFFERENCE
FROM TEACHERS t
JOIN COURSES c ON t.T_ID = c.C_TEACHER
JOIN GRADES g ON c.C_ID = g.G_COURSE
GROUP BY t.T_ID, t.T_NAME
ORDER BY DIFFERENCE DESC;   